# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Runner' do
use_frameworks!
use_modular_headers!

  # Flutter Pods
  use_flutter!
end

def use_flutter!
  target_path = File.expand_path('..', __dir__)
  flutter_podfile_setup = File.join(target_path, '.flutter-plugins-dependencies')

  # Podfile framework integration
  flutter_root = ENV['FLUTTER_ROOT']
  if flutter_root.nil?
    raise "FLUTTER_ROOT not found. Try running 'flutter doctor'."
  end

  # Include flutter pods
  load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
  flutter_install_all_ios_pods(target_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end